# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import proxy_pb2 as proxy__pb2


class InferenceProxyStub(object):
    """Define the gRPC service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.infer = channel.unary_unary(
                '/InferenceProxy/infer',
                request_serializer=proxy__pb2.InferenceMessage.SerializeToString,
                response_deserializer=proxy__pb2.InferenceRespose.FromString,
                )


class InferenceProxyServicer(object):
    """Define the gRPC service
    """

    def infer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InferenceProxyServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'infer': grpc.unary_unary_rpc_method_handler(
                    servicer.infer,
                    request_deserializer=proxy__pb2.InferenceMessage.FromString,
                    response_serializer=proxy__pb2.InferenceRespose.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'InferenceProxy', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class InferenceProxy(object):
    """Define the gRPC service
    """

    @staticmethod
    def infer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/InferenceProxy/infer',
            proxy__pb2.InferenceMessage.SerializeToString,
            proxy__pb2.InferenceRespose.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
