{
 "title": "scale-test-vdag-2:0.0.1-stable",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Inflight Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "aios_vdag_inflight_requests{vdagURI=\"scale-test-vdag-2:0.0.1-stable\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency in Seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "aios_vdag_inference_latency_seconds{vdagURI=\"scale-test-vdag-2:0.0.1-stable\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "aios_vdag_inference_requests_total{vdagURI=\"scale-test-vdag-2:0.0.1-stable\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "aios_vdag_inference_fps{vdagURI=\"scale-test-vdag-2:0.0.1-stable\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Complete Retries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "aios_vdag_metric_value{vdagURI=\"scale-test-vdag-2:0.0.1-stable\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "vdag_timestamp",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "aios_vdag_timestamp_seconds{vdagURI=\"scale-test-vdag-2:0.0.1-stable\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}