{
 "title": "VLLM mistralai/Magistral-Small-2506",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "load_balancer_quelength",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "aios_metric_value{blockId=\"magistral-small-2506-vllm-block\", instanceId=\"executor\", metric_key=\"queue_length.queue_length\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "end_to_end_count_total_per_instance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "aios_metric_value{blockId=\"magistral-small-2506-vllm-block\", metric_key=\"end_to_end_count_total\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "load_balancer_latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "aios_metric_value{blockId=\"magistral-small-2506-vllm-block\", instanceId=\"executor\", metric_key=\"latency.latency\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "end_to_end_count_sum",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by(metric_key) (aios_metric_value{blockId=\"magistral-small-2506-vllm-block\", metric_key=\"end_to_end_count_total\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "queue_length.average_1m_per_instance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "aios_metric_value{blockId=\"magistral-small-2506-vllm-block\", metric_key=\"queue_length.average_1m\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "end_to_end_count_aggregate",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aios_metric_value{blockId=\"magistral-small-2506-vllm-block\", metric_key=\"tasks_processed.tasks_processed_total\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "queue_length.current_per_instance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "aios_metric_value{blockId=\"magistral-small-2506-vllm-block\", metric_key=\"queue_length.current\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "end_to_end_latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "aios_metric_value{blockId=\"magistral-small-2506-vllm-block\", metric_key=\"end_to_end_latency\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "queue_length.average_1m_sum",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "sum by(metric_key) (aios_metric_value{blockId=\"magistral-small-2506-vllm-block\", metric_key=\"queue_length.average_1m\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "llm_inference_empty_token_total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "aios_metric_value{blockId=\"magistral-small-2506-vllm-block\", metric_key=\"llm_inference_empty_token_total\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "llm_tokens_per_second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "aios_metric_value{blockId=\"magistral-small-2506-vllm-block\", metric_key=\"llm_tokens_per_second\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "instance_count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "expr": "count(count by(instanceId) (aios_metric_value{blockId=\"magistral-small-2506-vllm-block\", instanceId!~\"executor\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "on_preprocess_latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "aios_metric_value{blockId=\"magistral-small-2506-vllm-block\", metric_key=\"on_preprocess_latency\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total_Tokens_generated",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "targets": [
    {
     "expr": "aios_metric_value{blockId=\"magistral-small-2506-vllm-block\", metric_key=\"llm_tokens_generated_total\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "on_preprocess_count_total_per_instance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "aios_metric_value{blockId=\"magistral-small-2506-vllm-block\", metric_key=\"on_preprocess_count_total\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total_Tokens_generated_aggregated",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "targets": [
    {
     "expr": "sum(sum by(metric_key) (aios_metric_value{blockId=\"magistral-small-2506-vllm-block\", metric_key=\"llm_tokens_generated_total\"}))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}