services:
  weaviate:
    command:
    - --host
    - 0.0.0.0
    - --port
    - '8080'
    - --scheme
    - http
    image: semitechnologies/weaviate:1.24.8
    ports:
      - "8080:8080"
      - "50051:50051"
    environment:
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'false' # Disable anonymous access
      AUTHENTICATION_CLIENT_CREDENTIALS_ENABLED: 'true' # Enable username/password auth
      AUTHENTICATION_CLIENT_CREDENTIALS_USERS: 'coguser1:sdf345BJw44HMy' # Add users

      QUERY_DEFAULTS_LIMIT: 25
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'none'
      ENABLE_MODULES: 'text2vec-cohere,text2vec-huggingface,text2vec-palm,text2vec-openai,generative-openai,generative-cohere,generative-palm,ref2vec-centroid,reranker-cohere,qna-openai'
      CLUSTER_HOSTNAME: 'node1'
      # Performance tuning
      GOGC: 100
      GOMEMLIMIT: 2GiB
      # Increase max connections for lower latency
      CONNECTIONS_MAX_IDLE: 100
      CONNECTIONS_MAX_OPEN: 200
      # Optional: tune batch size for imports
      BATCH_SIZE: 100
    volumes:
      - ./weaviate_data:/var/lib/weaviate
    restart: unless-stopped
