{
 "title": "VLLM Qwen/Qwen3.5-0.8B",
 "time": { "from": "2026-04-14T09:00:00.000Z", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "load_balancer_quelength",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "aios_metric_value{blockId=\"qwen3-5-0-8b-vllm-block\", instanceId=\"executor\", metric_key=\"queue_length.queue_length\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "end_to_end_count_total_per_instance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "aios_metric_value{blockId=\"qwen3-5-0-8b-vllm-block\", metric_key=\"end_to_end_count_total\"} and on(instanceId)\n(time() - aios_metric_value{blockId=\"qwen3-5-0-8b-vllm-block\", metric_key=\"timestamp\"} < $__range_s)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "load_balancer_latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "aios_metric_value{blockId=\"qwen3-5-0-8b-vllm-block\", instanceId=\"executor\", metric_key=\"latency.latency\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "end_to_end_count_sum",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by(metric_key) (aios_metric_value{blockId=\"qwen3-5-0-8b-vllm-block\", metric_key=\"end_to_end_count_total\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "queue_length.average_1m_per_instance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "aios_metric_value{blockId=\"qwen3-5-0-8b-vllm-block\", metric_key=\"queue_length.average_1m\"}\nand on(instanceId)\n(time() - aios_metric_value{blockId=\"qwen3-5-0-8b-vllm-block\", metric_key=\"timestamp\"} < $__range_s)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "task_process_total_by_block",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aios_metric_value{blockId=\"qwen3-5-0-8b-vllm-block\", metric_key=\"tasks_processed.tasks_processed_total\"}\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "queue_length.current_per_instance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "aios_metric_value{blockId=\"qwen3-5-0-8b-vllm-block\", metric_key=\"queue_length.current\"} and on(instanceId)\n(time() - aios_metric_value{blockId=\"qwen3-5-0-8b-vllm-block\", metric_key=\"timestamp\"} < $__range_s)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "tasks_processed_in_this_interval",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  increase(\n    aios_metric_value{blockId=\"qwen3-5-0-8b-vllm-block\", instanceId=\"executor\", metric_key=\"tasks_processed.tasks_processed_total\"}[$__range])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "queue_length.average_1m_sum",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "sum by(metric_key) (\n  aios_metric_value{blockId=\"qwen3-5-0-8b-vllm-block\", metric_key=\"queue_length.average_1m\"}\n  and on(instanceId) \n  (time() - aios_metric_value{blockId=\"qwen3-5-0-8b-vllm-block\", metric_key=\"timestamp\"} < $__range_s)\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "end_to_end_latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "aios_metric_value{blockId=\"qwen3-5-0-8b-vllm-block\", metric_key=\"end_to_end_latency\"} and on(instanceId)\n(time() - aios_metric_value{blockId=\"qwen3-5-0-8b-vllm-block\", metric_key=\"timestamp\"} < $__range_s)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "llm_tokens_per_second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "aios_metric_value{blockId=\"qwen3-5-0-8b-vllm-block\", metric_key=\"llm_tokens_per_second\"} and on(instanceId)\n(time() - aios_metric_value{blockId=\"qwen3-5-0-8b-vllm-block\", metric_key=\"timestamp\"} < $__range_s)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "llm_inference_empty_token_total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "expr": "aios_metric_value{blockId=\"qwen3-5-0-8b-vllm-block\", metric_key=\"llm_inference_empty_token_total\"} and on(instanceId)\n(time() - aios_metric_value{blockId=\"qwen3-5-0-8b-vllm-block\", metric_key=\"timestamp\"} < $__range_s)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Token_per_sec_summed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "sum(\n  rate(\n    aios_metric_value{blockId=\"qwen3-5-0-8b-vllm-block\", metric_key=\"llm_tokens_generated_total\"}[$__range])\n    and on(instanceId)\n    (time() - aios_metric_value{blockId=\"qwen3-5-0-8b-vllm-block\", metric_key=\"timestamp\"} < $__range_s)\n)"
    }
   ]
  },
  {
   "title": "instance_count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "targets": [
    {
     "expr": "count(\n  count by(instanceId) (\n    aios_metric_value{blockId=\"qwen3-5-0-8b-vllm-block\", instanceId!~\"executor\"}\n    and on(instanceId)\n    (time() - aios_metric_value{blockId=\"qwen3-5-0-8b-vllm-block\", metric_key=\"timestamp\"} < $__range_s)\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "on_preprocess_latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "aios_metric_value{blockId=\"qwen3-5-0-8b-vllm-block\", metric_key=\"on_preprocess_latency\"} and on(instanceId)\n(time() - aios_metric_value{blockId=\"qwen3-5-0-8b-vllm-block\", metric_key=\"timestamp\"} < $__range_s)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total_Tokens_generated",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "targets": [
    {
     "expr": "aios_metric_value{blockId=\"qwen3-5-0-8b-vllm-block\", metric_key=\"llm_tokens_generated_total\"} and on(instanceId)\n(time() - aios_metric_value{blockId=\"qwen3-5-0-8b-vllm-block\", metric_key=\"timestamp\"} < $__range_s)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "on_preprocess_count_total_per_instance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "targets": [
    {
     "expr": "aios_metric_value{blockId=\"qwen3-5-0-8b-vllm-block\", metric_key=\"on_preprocess_count_total\"} and on(instanceId)\n(time() - aios_metric_value{blockId=\"qwen3-5-0-8b-vllm-block\", metric_key=\"timestamp\"} < $__range_s)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total_Tokens_generated_aggregated",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "targets": [
    {
     "expr": "sum(\n  sum by(metric_key) (\n    aios_metric_value{blockId=\"qwen3-5-0-8b-vllm-block\", metric_key=\"llm_tokens_generated_total\"}\n    and on(instanceId)\n    (time() - aios_metric_value{blockId=\"qwen3-5-0-8b-vllm-block\", metric_key=\"timestamp\"} < $__range_s)\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}