# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proxy.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bproxy.proto\"$\n\x10InferenceMessage\x12\x10\n\x08rpc_data\x18\x01 \x01(\x0c\"#\n\x10InferenceRespose\x12\x0f\n\x07message\x18\x01 \x01(\x08\x32?\n\x0eInferenceProxy\x12-\n\x05infer\x12\x11.InferenceMessage\x1a\x11.InferenceResposeb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proxy_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_INFERENCEMESSAGE']._serialized_start=15
  _globals['_INFERENCEMESSAGE']._serialized_end=51
  _globals['_INFERENCERESPOSE']._serialized_start=53
  _globals['_INFERENCERESPOSE']._serialized_end=88
  _globals['_INFERENCEPROXY']._serialized_start=90
  _globals['_INFERENCEPROXY']._serialized_end=153
# @@protoc_insertion_point(module_scope)
