apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-inference-server
  namespace: inference-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-inference-server
  template:
    metadata:
      labels:
        app: demo-inference-server
    spec:
      containers:
        - name: demo-inference-server
          image: MANAGEMENTMASTER:31280/block/inference_server:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 50052 
            - containerPort: 20000
            - containerPort: 50060
          env:
            - name: INFERENCE_REDIS_HOST
              value: "DEMOMASTERNODE"
            - name: INFERENCE_REDIS_PORT
              value: "31502"
            - name: ADHOC_INSTANCE_ID
              value: "instance-2"
            - name: SEARCH_SERVER_API_URL
              value: "http://MANAGEMENTMASTER:30150"
            - name: INFERENCE_REDIS_INTERNAL_URL
              value: "localhost"
            - name: BLOCKS_DB_URL
              value: "http://MANAGEMENTMASTER:30100"
            - name: DISCOVERY_MODE
              value: "gateway"
            - name: INCLUSTER_REDIS_HOST
              value: demo-inference-server.inference-server.svc.cluster.local
            - name: CLUSTER_ID
              value: "gcp-demo-cluster"
        - name: redis
          image: redis:latest
          ports:
            - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: demo-inference-server
  namespace: inference-server
spec:
  selector:
    app: demo-inference-server
  ports:
    - name: grpc
      protocol: TCP
      port: 50052
      targetPort: 50052
      nodePort: 31500
    - name: rest
      protocol: TCP
      port: 20000
      targetPort: 20000
      nodePort: 31501
    - name: api
      protocol: TCP
      port: 50060
      targetPort: 50060
      nodePort: 31504
    - name: redis
      protocol: TCP
      port: 6379
      targetPort: 6379
      nodePort: 31502
  type: NodePort
